

service: final
# app and org for use with dashboard.serverless.com
app: final
org: cesaraguirre


provider:
  name: aws
  runtime: nodejs12.x

functions:

  hello-kaiser:
    handler: src/requestDNI/handler/createDNI.post
#    The following are a few example events you can configure
#    NOTE: Please make sure to change your handler code to work with those events
#    Check the event documentation for details
    events:
      - http:
          path: dni/create
          method: post

# resources:
#   Resources:
#     DNITable:
#       Type: AWS::DynamoDB::Table
#       Properties:
#         TableName: ${self:custom.DNITableName}
#         BillingMode: PAY_PER_REQUEST
#         AttributeDefinitions:
#           - AttributeName: pk
#             AttributeType: S
#           - AttributeName: sk
#             AttributeType: S
#         KeySchema:
#           - AttributeName: pk
#             KeyType: HASH
#           - AttributeName: sk
#             KeyType: RANGE
